version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - docker-compose-dev.env
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
