apiVersion: cert-manager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'alex@swipelab.co'
    privateKeySecretREf:
      name: letsencrypt-prod
    http01: {}